_target_: fgvc.models.plant_clef_model.VectorPlantCLEFModule

# criterian:
#   _target_: torch.nn.MultiLabelSoftMarginLoss
num_classes: &num_classes 7806

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 8.0e-05
  weight_decay: 0.01  # assuming a default since not specified

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 30  # Assuming training for 100 epochs, adjust as needed
  eta_min: 0  # Minimum learning rate at the end of training




# # compile model for faster training with pytorch 2.0
# compile: false
